### ISSUE TITLE
Не заработало

### ISSUE THREAD

**Issue by xsiruse** [Ground-Zerro/adgh-ipset-for-keenetic#1]
Так и не заработало. мало того, что инструкции AdGuard в своем FAQ для докера, так и после решения проблемы с первичной настройкой AdGuard добавление маршрутов так и не началось

**Comment by Ground-Zerro** [comment]
> Так и не заработало. мало того, что инструкции AdGuard в своем FAQ для докера, так и после решения проблемы с первичной настройкой AdGuard добавление маршрутов так и не началось

WG можно поставить из [этого репозитория](https://github.com/pivpn/pivpn). Легко ставится, настраивается при помощи пошагового мастера в псевдографическом режиме.

Этот репозиторий не проверен. В тестах некому участвовать..
[Попробуй по этой инструкции](https://taravasya.github.io/notes/keenetic/agh_keenetic). Скрипт написан по ней.

**Comment by xsiruse** [comment]
Пропущена строка в байпасерах:
`Создайте файл /opt/etc/ndm/netfilter.d/010-bypass.sh для ipv4 со следующим содержимым:

#!/bin/sh

[ "$type" == "ip6tables" ] && exit
[ "$table" != "mangle" ] && exit
[ -z "$(ipset --quiet list bypass)" ] && exit

if [ -z "$(iptables-save | grep bypass)" ]; then
     **mark_id=`curl -kfsS http://localhost:79/rci/show/ip/policy 2>/dev/null | jq -r '.[] | select(.description == "policy_vpn") | .mark'`**
     iptables -w -t mangle -A PREROUTING ! -i nwg0 -m conntrack --ctstate NEW -m set --match-set bypass dst -j CONNMARK --set-mark 0x$mark_id
     iptables -w -t mangle -A PREROUTING ! -i nwg0 -m set --match-set bypass dst -j CONNMARK --restore-mark
fi`

Мой интерфейс nwg1, т.к. это второй WireGuard. Хотя скрипт и спросил, какой надо использовать интерфейс, в файлы записалось всё равно nwg1. Стоит посмотреть на ошибки или сделать более универсальным. 
переменная select(.description == "policy_vpn") тоже может быть унифицирована.

**Comment by xsiruse** [comment]
кстати, пока сработало только с 2ip, ютюб так и не поднялся пока

**Comment by Ground-Zerro** [comment]
**Спасибо за обратную связь!**

> 1. Пропущена строка в байпасерах:
> 3\. Переменная в пропущенной строке select(.description == "policy_vpn") тоже может быть унифицирована.

Это сделано специально, чтобы маркирвоался весь трафик роутера для всех устройств, а не только устройств, помещенных в отдельную политику роутера.
Логика - вернуть доступ к закрытым ресурсам интернета, который соответственно был у всех устройств, до того как доступ кто-то и почему-то ограничил.

Если скрипт будет развиваться добавлю выбор - делать это только для выбранных клиентов сети через политику или для всех устройств подключенных к роутеру.

У меня на основном (и единственном) роутере в `/opt/etc/ndm/netfilter.d/010-bypass.sh` прописано и работает так:
```
#!/bin/sh

[ "$type" == "ip6tables" ] && exit
[ "$table" != "mangle" ] && exit
[ -z "$(ip link list | grep nwg0)" ] && exit
[ -z "$(ipset --quiet list bypass)" ] && exit

if [ -z "$(iptables-save | grep bypass)" ]; then
     iptables -w -t mangle -A PREROUTING ! -i nwg0 -m conntrack --ctstate NEW -m set --match-set bypass dst -j CONNMARK --set-mark 1001
     iptables -w -t mangle -A PREROUTING ! -i nwg0 -m set --match-set bypass dst -j CONNMARK --restore-mark
fi
```
Из кода выше - весь трафик всех устройств роутера к узлам, указанным в `ipset`, маркируется и перенаправляется через `nwg0`.
По факту, у меня, трафик маркируется, сайты из `ipset` открываются через vpn.


> 2\. Мой интерфейс nwg1, т.к. это второй WireGuard. Хотя скрипт и спросил, какой надо использовать интерфейс, в файлы записалось всё равно nwg1.

Можно здесь немного подробней? Не совсем понял, что произошло. Написано, что выбрал nwg1 и он же (nwg1) и прописался.
В этом месте был основной затык в скрипте. Если брать интерфейс из системы то в переменную попадает мусор и соответственно ничего не работает, поэтому сделано что выводится список и пользователь сам набирает на клавиатуре название интерфейса, после чего просто проверяется есть ли то, что ввел пользователь в списке или нет.
Это явно нужно дорабатывать, но пока получается что даже база не функционирует как нужно.

> кстати, пока сработало только с 2ip, ютюб так и не поднялся пока

В `/opt/etc/AdGuardHome/ipset.conf` должно прописаться:
```
2ip.ru/bypass,bypass6
google.com,googlevideo.com,ggpht.com,ytimg.com,youtube.com,youtubei.googleapis.com,youtu.be,nhacmp3youtube.com,googleusercontent.com,gstatic.com/bypass,bypass6
openai.com,chatgpt.com/bypass,bypass6
bookstagram.com,carstagram.com,cdninstagram.com,chickstagram.com,ig.me,igcdn.com,igsonar.com,igtv.com,imstagram.com,imtagram.com,instaadder.com,instachecker.com,instafallow.com,instafollower.com,inst>
1337x.to,262203.game4you.top,eztv.re,fitgirl-repacks.site,new.megashara.net,nnmclub.to,nnm-club.to,nnm-club.me,rarbg.to,rustorka.com,rutor.info,rutor.org,rutracker.cc,rutracker.org,static.rutracker.c>
github.com/bypass,bypass6
keenetic.com/bypass,bypass6
```
Странно, что 2ip проходит, а остальное нет. Может провайдер DNS подменяет? У меня было так, провайдер подменял например `youtube.com` на `127.0.0.1`, пока в ADGH не убрал все простые DNS сервера и добавил только шифрованные.
Сейчас в ADGH на рабочем роутере включены только:
```
tls://dns.google
tls://one.one.one.one
tls://p0.freedns.controld.com
tls://dot.sb
tls://dns.nextdns.io
tls://dns.quad9.net
```
Попробуй так настроить:
![DNS](https://github.com/user-attachments/assets/793cc690-6e03-4c62-a5f7-5b3a27a0746d)

**Comment by Ground-Zerro** [comment]
Похоже нашел ошибку.
В файле `/opt/etc/AdGuardHome/AdGuardHome.yaml` при определенных условиях мог неправильно прописываться путь к `ipset`
Исправил.

Еще при установке добавил шифрованные DNS сервера с удалением DNS серверов без защиты.

**Comment by xsiruse** [comment]
так, ну хорошо, опишу свои условия, может это натолкнёт:

1. пара роутер и ретранслятор
2. ISP через SFP оптический
3. три VPN, из них два WireGuard и только один для интернета на nwg1
4. в политике по умолчанию стоит итого два интерфейса для интернет ISP и WG 
5. ISP в первом прио, WG во втором, иначе, если WG будет первым, то весь трафик завернется на него.

пробовал с прописанием отдельной политики, где был только WG и без клиентов, фокус с ipset сработал, но только для 2ip.ru. Остальные сайты из списка не работали. 

на примере youtube понял, что AdGH выдает резолвы в ipv6, но вот беда, правила маршрутизации с отметкой bypass6 пустые
![image](https://github.com/user-attachments/assets/1dc8c848-f8ac-491e-9185-dba23afe86be)

**Comment by Ground-Zerro** [comment]
А у WG есть ipv6?
Чтоб WG работал с ним в конфиге также должен быть указан IPv6 адрес сервера и на самом сервере должна быть правильно настроена его маршрутизация.
Хоть и подразумевается, что в случае отсутствия доступа к ресурсу по IPv6 автоматически будет использован IPv4 адрес но мало-ли.


Предлагаю сделать все еще раз, в скрипте были исправлены некоторые ошибки и неточности.
```
curl -L -s "https://raw.githubusercontent.com/Ground-Zerro/adgh-ipset-for-keenetic/refs/heads/main/adgh-ipset.sh" > /tmp/adgh-ipset.sh && chmod +x /tmp/adgh-ipset.sh && sh /tmp/adgh-ipset.sh
```
Если не сработает то есть еще догадка:
На форуме это стало часто обсуждаться. Некоторые программы и устройства, в т.ч. Андройд и Apple,  используют свои DNS. Называются как правило "Защищённые DNS" или "Безопасные DNS".
А для используемого способа критически важно чтобы DNS запрос пришел именно на ADGH, это запускает всю цепочку скриптов и срабатывания правил.
В случае когда браузер или смартфон использует свой DNS весь этот дополнительный софт в роутере остается в стороне, потому что он просто не знает к какому домену обращается клиент.

Вот пример для Яндекс браузера:
![DNS](https://github.com/user-attachments/assets/a5c2abf7-4460-4b80-a255-35305105c301)
Если галочку поставить то IPSet и AdGuard Home просто не будут знать какой трафик перенаправлять через указанный туннель.

**Comment by xsiruse** [comment]
> Предлагаю сделать все еще раз, в скрипте были исправлены некоторые ошибки и неточности.
это помогло, правда не сразу, роутер пришлось ребутнуть.

> Чтоб WG работал с ним в конфиге пира (*.conf файл) также должен быть указан IPv6 адрес сервера 
да, в конфиге нет ipv6, но это уже и не нужно, выходит, т.к. см. выше

Короче, спасибо. Буду тестить дальше, открою новые кейсы, если что найду.

**Comment by Ground-Zerro** [comment]
@xsiruse 
> это помогло

Вот и хорошо.

> Буду тестить дальше, открою новые кейсы, если что найду.

Спасибо за помощь в тестировании.

Отправлю скрипт в прод.

В будущем возможно прикручу возможность выбора маршрутизации на основе политик доступа. Чтоб можно было выбрать к каким устройствам в сети применять маршрутизацию.
